import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/fonts/font";
import Navbar from "@/components/Navbar";
import { AuthSessionProvider } from "@/context/Authenticate";
import { BlogContextProvider } from "@/context/ProductContext";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "ZemBlog is a Creative Blogging site 2024",
  description: "Generated by next js and typescript",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthSessionProvider>
          <BlogContextProvider>
            <Navbar />
            {children}
            <Toaster richColors position="top-center" visibleToasts={3} />
          </BlogContextProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
